[[redirects]]
  from = "/api/*"
  to = "https://rolling-2szg.onrender.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200